version: '3.3'


services:
  web:
    build: .
    image: zoobych/hosting:v0.1.0
    ports:
      - "80:25000"
    environment:
      - DB_PASSWORD=db_password
      - DB_USER=db_user
      - DB_NAME=db_name

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db_name

